/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nitro.cloud;

public final class TaskResult {
  public final static TaskResult Canceled = new TaskResult("Canceled");
  public final static TaskResult Succeeded = new TaskResult("Succeeded");
  public final static TaskResult Failed = new TaskResult("Failed");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TaskResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TaskResult.class + " with value " + swigValue);
  }

  private TaskResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TaskResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TaskResult(String swigName, TaskResult swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TaskResult[] swigValues = { Canceled, Succeeded, Failed };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

