/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nitro.cloud;

public final class TaskCallbackCommnad {
  public final static TaskCallbackCommnad TaskNotImplemented = new TaskCallbackCommnad("TaskNotImplemented");
  public final static TaskCallbackCommnad TaskContinue = new TaskCallbackCommnad("TaskContinue");
  public final static TaskCallbackCommnad TaskCancel = new TaskCallbackCommnad("TaskCancel");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TaskCallbackCommnad swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TaskCallbackCommnad.class + " with value " + swigValue);
  }

  private TaskCallbackCommnad(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TaskCallbackCommnad(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TaskCallbackCommnad(String swigName, TaskCallbackCommnad swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TaskCallbackCommnad[] swigValues = { TaskNotImplemented, TaskContinue, TaskCancel };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

