/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nitro.cloud;

public class TaskSwig extends Task {
  private transient long swigCPtr;

  protected TaskSwig(long cPtr, boolean cMemoryOwn) {
    super(nitro_cloudJNI.TaskSwig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TaskSwig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nitro_cloudJNI.delete_TaskSwig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    nitro_cloudJNI.TaskSwig_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    nitro_cloudJNI.TaskSwig_change_ownership(this, swigCPtr, true);
  }

  public TaskSwig(int sleepCount, int failedStep) {
    this(nitro_cloudJNI.new_TaskSwig__SWIG_0(sleepCount, failedStep), true);
    nitro_cloudJNI.TaskSwig_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public TaskSwig(int sleepCount) {
    this(nitro_cloudJNI.new_TaskSwig__SWIG_1(sleepCount), true);
    nitro_cloudJNI.TaskSwig_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public TaskCallbackCommnad OnStarted(int taskId, String someMessage) {
    return TaskCallbackCommnad.swigToEnum((getClass() == TaskSwig.class) ? nitro_cloudJNI.TaskSwig_OnStarted(swigCPtr, this, taskId, someMessage) : nitro_cloudJNI.TaskSwig_OnStartedSwigExplicitTaskSwig(swigCPtr, this, taskId, someMessage));
  }

  public TaskCallbackCommnad OnProgress(int progress, int upperBound, String someMessage) {
    return TaskCallbackCommnad.swigToEnum((getClass() == TaskSwig.class) ? nitro_cloudJNI.TaskSwig_OnProgress(swigCPtr, this, progress, upperBound, someMessage) : nitro_cloudJNI.TaskSwig_OnProgressSwigExplicitTaskSwig(swigCPtr, this, progress, upperBound, someMessage));
  }

  public void OnFinished(TaskResult taskResult, String someMessage) {
    if (getClass() == TaskSwig.class) nitro_cloudJNI.TaskSwig_OnFinished(swigCPtr, this, taskResult.swigValue(), someMessage); else nitro_cloudJNI.TaskSwig_OnFinishedSwigExplicitTaskSwig(swigCPtr, this, taskResult.swigValue(), someMessage);
  }

}
